platformName: "Android"
platformVersion: "7.1.2"
deviceName: "127.0.0.1:62001"
app: "d:\\111\\atstudy.apk"
appPackage: "com.atstudy.ando"
appActivity: "com.atstudy.ando.ui.MainActivity"
noReset: "false"